In [57]:
from dataset import *
import os
import time
import datetime
import torch
import torch.optim as optim
import torch.optim.lr_scheduler as lr_scheduler
from torch.utils.data import DataLoader
from torchvision import transforms
import numpy as np
from Utils import *
from Loss import *
import SimpleITK as sitk
import nibabel as nib

In [58]:
a1 = load_nii('/home/user/Documents/dataset/oasis_seg/OASIS_OAS1_0001_MR1/aligned_norm.nii.gz')
b1 = nib.load('/home/user/Documents/dataset/oasis_seg/OASIS_OAS1_0001_MR1/aligned_norm.nii.gz')
# b1 = nib.load('/home/user/Documents/dataset/Mindboggle101/mindboggle/label_31_reID_merged/OASIS-TRT-20-2.nii.gz')

In [59]:
c1=np.copy(b1.affine)
c1[1:3]=c1[2:0:-1]
c1[1]=-c1[1]
print(c1)

[[  -1.    0.    0.   80.]
 [  -0.    1.   -0.  -96.]
 [   0.    0.    1. -112.]
 [   0.    0.    0.    1.]]


In [60]:
b1.affine

array([[  -1.,    0.,    0.,   80.],
       [   0.,    0.,    1., -112.],
       [   0.,   -1.,    0.,   96.],
       [   0.,    0.,    0.,    1.]])

In [61]:
b1.get_fdata().shape

(160, 192, 224)

In [63]:
a2=np.transpose(a1,(0,2,1))
a2= np.flip(a2,axis=2)
nib.Nifti1Image(a2,c1).to_filename('/home/user/Documents/dataset/oasis_seg/OASIS_OAS1_0001_MR1/test.nii.gz')

In [3]:
class_name={k: str(k) for k in range(1, 32)}
print(class_name)

{1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10', 11: '11', 12: '12', 13: '13', 14: '14', 15: '15', 16: '16', 17: '17', 18: '18', 19: '19', 20: '20', 21: '21', 22: '22', 23: '23', 24: '24', 25: '25', 26: '26', 27: '27', 28: '28', 29: '29', 30: '30', 31: '31'}
